# Generated by Django 4.0.4 on 2022-06-15 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_project_user_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
